shallow_clone: false

clone_script:
- cmd: >-
    git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
    cd %APPVEYOR_BUILD_FOLDER%
    git checkout -qf %APPVEYOR_REPO_COMMIT%
    git submodule update --init --recursive

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

image:
  - Visual Studio 2015
  - Visual Studio 2017

cache:
  - C:\cmake-3.10.0-win64-x64

install:
  - ps: |
      if (![IO.File]::Exists("C:\cmake-3.10.0-win64-x64\bin\cmake.exe")) {
        Start-FileDownload 'https://cmake.org/files/v3.10/cmake-3.10.0-win64-x64.zip'
        7z x -y cmake-3.10.0-win64-x64.zip -oC:\
      }
      $env:PATH="C:\cmake-3.10.0-win64-x64\bin;$env:PATH"

build_script:
  - ps: |
      if ("$env:APPVEYOR_JOB_NAME" -match "Image: Visual Studio 2015") {
          .\build.ps1 -VisualStudioVersion Vs2015
      } else {
          .\build.ps1 -VisualStudioVersion Vs2017
      }

#test_script:
#  - ps: |
#      $test_dir = 'build_' + $VisualStudioVersion + '_' + $Platform + '_' + $Runtime

deploy: off