version: '{build}-{branch}'

shallow_clone: false

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

image:
  - Visual Studio 2015
  - Visual Studio 2017

cache:
  - C:\cmake-3.10.0-win64-x64

install:
  - git submodule update --init --recursive
  - ps: |
      if (![IO.File]::Exists("C:\cmake-3.10.0-win64-x64\bin\cmake.exe")) {
        Start-FileDownload 'https://cmake.org/files/v3.10/cmake-3.10.0-win64-x64.zip'
        7z x -y cmake-3.10.0-win64-x64.zip -oC:\
      }
      $env:PATH="C:\cmake-3.10.0-win64-x64\bin;$env:PATH"

build_script:
  - ps: |
      if ("$env:APPVEYOR_JOB_NAME" -match "Image: Visual Studio 2015") {
          .\build.ps1 -VisualStudioVersion Vs2015 -Runtime Static -Platform $env:PLATFORM -Config $env:CONFIGURATION
      } else {
          .\build.ps1 -VisualStudioVersion Vs2017 -Runtime Static -Platform $env:PLATFORM -Config $env:CONFIGURATION
      }

test_script:
  - ps: |
      if ("$env:APPVEYOR_JOB_NAME" -match "Image: Visual Studio 2015") {
          $TestExecutable = 'build_Vs2015_' + $env:PLATFORM + '_static\test\lib\' + $env:CONFIGURATION + '\lib_tests.exe'
      } else {
          $TestExecutable = 'build_Vs2017_' + $env:PLATFORM + '_static\test\lib\' + $env:CONFIGURATION + '\lib_tests.exe'
      }
      Invoke-Expression $TestExecutable

deploy: off

notifications:
  - provider: Email
    to:
      - lordjeb@lordjeb.com
    subject: 'Build {{status}}'
    message: "{{message}}, {{commitId}}, ..."
    on_build_status_changed: true

deploy:
  release: win32cpp-v$(appveyor_build_version)
  description: 'win32cpp release $(appveyor_build_version)'
  provider: GitHub
  auth_token:
    secure: fYGohnQpLx+RWoPGxAbOTU9QdFePPcqYEpfjXQskzIRzMpoh1roRckyTNAJZb7RM
  artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
