# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    vs2017-x86:
      imageName: 'vs2017-win2016'
      PLATFORM: 'Win32'
      CONFIGURATION: 'Debug'
      VSVER: 'Vs2017'
    vs2017-x64:
      imageName: 'vs2017-win2016'
      PLATFORM: 'x64'
      CONFIGURATION: 'Debug'
      VSVER: 'Vs2017'

pool:
  vmImage: $(imageName)

steps:
- checkout: self
  clean: true
  submodules: true

- powershell: |
    if (![IO.File]::Exists("C:\cmake-3.10.0-win64-x64\bin\cmake.exe")) {
      Start-FileDownload 'https://cmake.org/files/v3.10/cmake-3.10.0-win64-x64.zip'
      7z x -y cmake-3.10.0-win64-x64.zip -oC:\
    }
    $env:PATH="C:\cmake-3.10.0-win64-x64\bin;$env:PATH"

- powershell: |
    .\build.ps1 -VisualStudioVersion $env:VSVER -Runtime Static -Platform $env:PLATFORM -Config $env:CONFIGURATION
